### ISSUE TITLE
Add origin story to foundational messaging

### ISSUE THREAD

**Issue by noahpierau** [decredcommunity/outreach#5]
Decred's creation story is considered to be compelling. It is rooted in the same tradition as Bitcoin and Monero, which will make the project stand out among other cryptocurrencies. 

Quotes from the matrix #proposals chat: 

> "perhaps i'm biased, as i've been going more down that rabbit hole lately, but it seems only a small number of projects have real cypherpunk cred. bitcoin, monero, decred, maybe zcash. that's about it. nothing else is really worth the time (unless smart contract unicorns are your thing)." 

> "Agreed, I think the cyperpunk narrative is extremely compelling. Spreading the origin story (which is hectic btw) will be an attractor." 

> "spreading the mysterious origin story with TT + _ingsoc is definitely a good idea. I didn't like that some of the newer articles presented Jake (or C0) as the founder. focusing on the origin story will hopefully give us more cypherpunk cred" 

Based on this discussion, the origin story could become part of the messaging doc.

**Comment by xaur** [comment]
Good idea! Pinging @liz-bagot and @Dustorf for comments as original curators of the foundational messaging doc. If anyone is up to craft a pull request please feel free to do so.

**Comment by noahpierau** [comment]
This [FAQ post](https://medium.com/@NoahPierau/what-is-decred-dcr-why-was-this-cryptocurrency-created-4e5cae085bc7) tells the story:

The origin of Decred can be traced back to 2013, when an anonymous Bitcointalk user named ‘tacotime’ started a thread and published the whitepaper for Memcoin2 (MC2). Tacotime worked alongside ‘_ingsoc’, another anonymous user. At the start of 2014 it appeared that tacotime also began work on another popular cryptocurrency: Monero.

_ingsoc approached Jake Yocom-Piatt, the CEO of Company Zero, with tacotime’s MC2 concept. At the time Company Zero was primarily focused on the development of btcsuite, an alternative full node Bitcoin implementation written in Go. Their code is highly-regarded in the crypto community and used by many leading projects such as Ethereum, BitGo, Factom, OpenBazaar and the Lightning Network. Eventually the two teams joined forces to develop Decred.

**Comment by noahpierau** [comment]
we have a history page now. closing issue
